
name: Password

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print Password
        env:
          MY_PASSWORD: ${{ secrets.PASSWORD }}
        run: echo My password is $MY_PASSWORD
